"""
K3NG Configuration Tool - Test Report Generator
Generates HTML reports from test results
"""

from pathlib import Path
from datetime import datetime
from typing import List

from .test_base import TestSuiteResult, TestResult, TestStatus


def generate_html_report(result: TestSuiteResult, output_file: str):
    """
    Generate HTML test report

    Args:
        result: TestSuiteResult to generate report from
        output_file: Path to output HTML file
    """
    html = _generate_html(result)

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(html)


def _generate_html(result: TestSuiteResult) -> str:
    """Generate HTML content"""
    return f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{result.name} - Test Report</title>
    <style>
        {_get_css()}
    </style>
</head>
<body>
    <div class="container">
        <h1>K3NG Hardware Test Report</h1>

        <div class="summary">
            <h2>Summary</h2>
            <table>
                <tr><td>Suite Name:</td><td>{result.name}</td></tr>
                <tr><td>Execution Time:</td><td>{result.start_time.strftime('%Y-%m-%d %H:%M:%S')}</td></tr>
                <tr><td>Duration:</td><td>{result.duration:.2f}s</td></tr>
                <tr><td>Total Tests:</td><td>{result.total_tests}</td></tr>
                <tr class="passed"><td>Passed:</td><td>{result.passed_tests}</td></tr>
                <tr class="failed"><td>Failed:</td><td>{result.failed_tests}</td></tr>
                <tr class="skipped"><td>Skipped:</td><td>{result.skipped_tests}</td></tr>
                <tr class="error"><td>Errors:</td><td>{result.error_tests}</td></tr>
                <tr><td>Success Rate:</td><td>{result.success_rate:.1f}%</td></tr>
            </table>
        </div>

        <div class="results">
            <h2>Test Results</h2>
            {_generate_results_html(result.test_results)}
        </div>

        <div class="footer">
            <p>Generated by K3NG Configuration Tool on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        </div>
    </div>
</body>
</html>
"""


def _generate_results_html(test_results: List[TestResult]) -> str:
    """Generate HTML for test results"""
    html_parts = []

    for test in test_results:
        status_class = _get_status_class(test.status)
        status_symbol = _get_status_symbol(test.status)

        html_parts.append(f"""
        <div class="test-result {status_class}">
            <div class="test-header">
                <span class="status-symbol">{status_symbol}</span>
                <span class="test-name">{test.name}</span>
                <span class="test-duration">{test.duration:.2f}s</span>
            </div>
            """)

        if test.message:
            html_parts.append(f'<div class="test-message">{test.message}</div>')

        if test.details:
            html_parts.append(f'<div class="test-details"><pre>{test.details}</pre></div>')

        if test.expected is not None and test.actual is not None:
            html_parts.append(f"""
            <div class="test-comparison">
                <div>Expected: <code>{test.expected}</code></div>
                <div>Actual: <code>{test.actual}</code></div>
            </div>
            """)

        if test.error:
            html_parts.append(f'<div class="test-error"><pre>{str(test.error)}</pre></div>')

        html_parts.append('</div>')

    return '\n'.join(html_parts)


def _get_status_class(status: TestStatus) -> str:
    """Get CSS class for status"""
    return {
        TestStatus.PASSED: "passed",
        TestStatus.FAILED: "failed",
        TestStatus.SKIPPED: "skipped",
        TestStatus.ERROR: "error",
        TestStatus.PENDING: "pending",
        TestStatus.RUNNING: "running",
    }.get(status, "unknown")


def _get_status_symbol(status: TestStatus) -> str:
    """Get symbol for status"""
    return {
        TestStatus.PASSED: "✓",
        TestStatus.FAILED: "✗",
        TestStatus.SKIPPED: "⊝",
        TestStatus.ERROR: "⚠",
        TestStatus.PENDING: "○",
        TestStatus.RUNNING: "⟳",
    }.get(status, "?")


def _get_css() -> str:
    """Get CSS styles"""
    return """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            line-height: 1.6;
            color: #333;
            background-color: #f5f5f5;
            padding: 20px;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            background-color: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }

        h1 {
            color: #2c3e50;
            margin-bottom: 30px;
            padding-bottom: 15px;
            border-bottom: 3px solid #3498db;
        }

        h2 {
            color: #34495e;
            margin-top: 30px;
            margin-bottom: 15px;
        }

        .summary {
            background-color: #ecf0f1;
            padding: 20px;
            border-radius: 5px;
            margin-bottom: 30px;
        }

        .summary table {
            width: 100%;
            border-collapse: collapse;
        }

        .summary td {
            padding: 8px;
            border-bottom: 1px solid #bdc3c7;
        }

        .summary td:first-child {
            font-weight: bold;
            width: 200px;
        }

        .summary tr.passed td:last-child {
            color: #27ae60;
            font-weight: bold;
        }

        .summary tr.failed td:last-child {
            color: #c0392b;
            font-weight: bold;
        }

        .summary tr.skipped td:last-child {
            color: #e67e22;
            font-weight: bold;
        }

        .summary tr.error td:last-child {
            color: #e74c3c;
            font-weight: bold;
        }

        .test-result {
            margin-bottom: 15px;
            padding: 15px;
            border-radius: 5px;
            border-left: 4px solid #95a5a6;
        }

        .test-result.passed {
            background-color: #d5f4e6;
            border-left-color: #27ae60;
        }

        .test-result.failed {
            background-color: #fadbd8;
            border-left-color: #c0392b;
        }

        .test-result.skipped {
            background-color: #fdebd0;
            border-left-color: #e67e22;
        }

        .test-result.error {
            background-color: #f8d7da;
            border-left-color: #e74c3c;
        }

        .test-header {
            display: flex;
            align-items: center;
            gap: 10px;
            margin-bottom: 10px;
        }

        .status-symbol {
            font-size: 20px;
            font-weight: bold;
        }

        .test-result.passed .status-symbol {
            color: #27ae60;
        }

        .test-result.failed .status-symbol {
            color: #c0392b;
        }

        .test-result.skipped .status-symbol {
            color: #e67e22;
        }

        .test-result.error .status-symbol {
            color: #e74c3c;
        }

        .test-name {
            flex-grow: 1;
            font-weight: bold;
        }

        .test-duration {
            color: #7f8c8d;
            font-size: 0.9em;
        }

        .test-message {
            margin-top: 10px;
            padding: 10px;
            background-color: rgba(255,255,255,0.5);
            border-radius: 3px;
        }

        .test-details, .test-error {
            margin-top: 10px;
            padding: 10px;
            background-color: #2c3e50;
            color: #ecf0f1;
            border-radius: 3px;
            overflow-x: auto;
        }

        .test-details pre, .test-error pre {
            margin: 0;
            font-family: 'Courier New', monospace;
            font-size: 0.9em;
        }

        .test-comparison {
            margin-top: 10px;
            padding: 10px;
            background-color: rgba(0,0,0,0.05);
            border-radius: 3px;
        }

        .test-comparison code {
            background-color: #34495e;
            color: #ecf0f1;
            padding: 2px 6px;
            border-radius: 3px;
            font-family: 'Courier New', monospace;
        }

        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ecf0f1;
            text-align: center;
            color: #7f8c8d;
            font-size: 0.9em;
        }
    """
